service: xana-media-handler-python
frameworkVersion: "3"

provider:
  name: aws
  stage: dev
  region: us-east-1

  # you can add statements to the Lambda function's IAM Role here
  iam:
    role: arn:aws:lambda:us-east-1:845847047647:layer:pillow:1

package:
  patterns:
    - "!node_modules"
      #  - '!exclude-me-dir/**'
    - "!requirements.txt"
    #  - include-me-dir/**

functions:
  dev-xana-py-image-compressor:
    name: dev-xana-py-image-compressor
    runtime: python3.8
    description: Lambda to compress image using python PIL library
    handler: handler.process_image
    layers:
      - arn:aws:lambda:us-east-1:845847047647:layer:pillow:1
    events:
      - s3:
          bucket: api-test-xana
          event: s3:objectCreated:*
          rules:
            - prefix: apitestxana/input/images
          existing: true
